language: python

python:
    - "3.6"
install:
    - pip3 install conan
    - conan profile new default --detect
    - conan profile update settings.compiler.libcxx=libstdc++11 default
    - conan create . user/testing

script:
    - conan test tests/ CubicInterpolation/0.1@user/testing
